### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by HuangShun** [elvis972602/Kemono-scraper#34]
Downloading Coomer
fetching creator list...
panic: unmarshal creator list error: invalid character '<' looking for beginning of value

goroutine 1 [running]:
github.com/elvis972602/kemono-scraper/kemono.(*Kemono).Start(0xc000071ae0)
        C:/Users/elvis/GolandProjects/Kemono-scraper/kemono/kemono.go:225 +0x111e
main.main()
        C:/Users/elvis/GolandProjects/Kemono-scraper/main/main.go:484 +0x3ca5

**Comment by mookau** [comment]
It appears they changed their API address. The address needs to be updated to "/api/**_v1/_**".

**Comment by mookau** [comment]
I've made a fork with the changes, and created a pull request. (Hopefully I've done it all correctly.)

In the meantime, for those unwilling to build from source, I've built the binaries with the changes: 
https://github.com/mookau/Kemono-scraper/releases

**Comment by HuangShun** [comment]
> I've made a fork with the changes, and created a pull request. (Hopefully I've done it all correctly.)
> 
> In the meantime, for those unwilling to build from source, I've built the binaries with the changes: https://github.com/mookau/Kemono-scraper/releases

It has same problem

**Comment by mookau** [comment]
> > I've made a fork with the changes, and created a pull request. (Hopefully I've done it all correctly.)
> > In the meantime, for those unwilling to build from source, I've built the binaries with the changes: https://github.com/mookau/Kemono-scraper/releases
> 
> It has same problem

Whoops, uploaded the old binaries by mistake. Should be fixed now.

**Comment by elvis972602** [comment]
Thanks mookau! 
It looks like some of the api's have been changed, so it's possible that there's still a problem, and I'll try to fix it as soon as I can.

**Comment by mookau** [comment]
It was very minor, but I'm glad to help.
